# Generated by Django 4.1 on 2022-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="job_reponsibility",
            new_name="job_responsibility",
        ),
        migrations.AlterField(
            model_name="job",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建日期"),
        ),
        migrations.AlterField(
            model_name="job",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, verbose_name="更改时间"),
        ),
    ]
