# Generated by Django 4.1 on 2022-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userid",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="应聘者ID"
                    ),
                ),
                ("username", models.CharField(max_length=135, verbose_name="姓名")),
                ("city", models.CharField(max_length=135, verbose_name="城市")),
                ("phone", models.CharField(max_length=135, verbose_name="手机号码")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=135, verbose_name="邮箱"),
                ),
                (
                    "apply_position",
                    models.CharField(blank=True, max_length=135, verbose_name="应聘职位"),
                ),
                (
                    "born_address",
                    models.CharField(blank=True, max_length=135, verbose_name="生源地"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=135, verbose_name="性别"),
                ),
                (
                    "candidate_remark",
                    models.CharField(
                        blank=True, max_length=135, verbose_name="候选人信息备注"
                    ),
                ),
                (
                    "bachelor_school",
                    models.CharField(blank=True, max_length=135, verbose_name="本科学校"),
                ),
                (
                    "master_school",
                    models.CharField(blank=True, max_length=135, verbose_name="研究生学校"),
                ),
                (
                    "doctor_school",
                    models.CharField(blank=True, max_length=135, verbose_name="博士生学校"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=135, verbose_name="专业"),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True,
                        choices=[("本科", "本科"), ("硕士", "硕士"), ("博士", "博士")],
                        max_length=135,
                        verbose_name="学历",
                    ),
                ),
                (
                    "test_score_of_general_ability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="综合能力测评成绩",
                    ),
                ),
                (
                    "paper_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="笔试成绩",
                    ),
                ),
                (
                    "first_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="初试分",
                    ),
                ),
                (
                    "first_learning_ability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="学习能力得分",
                    ),
                ),
                (
                    "first_professional_competency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="专业能力得分",
                    ),
                ),
                (
                    "first_advantage",
                    models.TextField(blank=True, max_length=1024, verbose_name="优势"),
                ),
                (
                    "first_disadvantage",
                    models.TextField(blank=True, max_length=1024, verbose_name="顾虑和不足"),
                ),
                (
                    "first_result",
                    models.CharField(
                        blank=True,
                        choices=[("建议复试", "建议复试"), ("待定", "待定"), ("放弃", "放弃")],
                        max_length=256,
                        verbose_name="初试结果",
                    ),
                ),
                (
                    "first_recommend_position",
                    models.CharField(blank=True, max_length=256, verbose_name="推荐部门"),
                ),
                (
                    "first_interviewer",
                    models.CharField(blank=True, max_length=256, verbose_name="面试官"),
                ),
                (
                    "first_remark",
                    models.CharField(blank=True, max_length=135, verbose_name="初始备注"),
                ),
                (
                    "second_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="专业复试得分",
                    ),
                ),
                (
                    "second_learning_ability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="学习能力得分",
                    ),
                ),
                (
                    "second_professional_competency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="专业能力得分",
                    ),
                ),
            ],
            options={
                "verbose_name": "应聘者",
                "verbose_name_plural": "应聘者",
                "db_table": "candidate",
            },
        ),
    ]
